- name: Add WARP GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
- name: Add WARP repo
  ansible.builtin.apt_repository:
    filename: cloudflare-client
    repo: "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ {{ ansible_facts['distribution_release'] }} main"
- name: Install cloudflare-warp
  apt:
    name: cloudflare-warp
    state: present
    update_cache: yes
- name: Register WARP
  shell:
    cmd: echo "y" | warp-cli registration new
- name: Set WARP proxy mode
  shell:
    cmd: warp-cli mode proxy
- name: Set WARP proxy port
  shell:
    cmd: warp-cli proxy port 40000
- name: Connect WARP
  shell:
    cmd: warp-cli connect
