#!/usr/bin/env python3
"""Interactive settings; all persistent credentials are generated by secrets."""
import json
import getpass
import ipaddress
import os
from pathlib import Path
import secrets
import sys
from setup_config import domain, new_state, save_json, ssh_port, validate_state


def ask(prompt, default=''):
    value = input(f'{prompt}' + (f' [{default}]' if default else '') + ': ').strip()
    return value or default


def yes(prompt):
    return ask(prompt + ' [y/N]').lower() == 'y'


def configure_proxy(state):
    previous = state.get('egress_proxy') or {}
    choice = ask('External proxy for all VPN traffic? y/n', 'y' if previous else 'n').lower()
    if choice not in ('y', 'n'):
        raise ValueError('Answer y or n for the external proxy')
    if choice == 'n':
        state['egress_proxy'] = None
        return
    if state['mode'] == 'marzban':
        print('This changes VPN egress for the panel AND its connected nodes.')
    protocol = ask('Proxy protocol: socks or http', previous.get('protocol', 'socks')).lower()
    address = ask('Proxy hostname or IP (without URL scheme)', previous.get('address', ''))
    try:
        address = str(ipaddress.ip_address(address))
    except ValueError:
        address = domain(address)
    port = ask('Proxy port', str(previous.get('port', '')))
    if not port.isascii() or not port.isdecimal() or len(port) > 5:
        raise ValueError('Proxy port must contain decimal digits only')
    auth = ask('Use proxy authentication? y/n', 'y' if previous.get('user') else 'n').lower()
    if auth not in ('y', 'n'):
        raise ValueError('Answer y or n for proxy authentication')
    user = ask('Proxy username', previous.get('user', '')) if auth == 'y' else ''
    if auth == 'y' and not user:
        raise ValueError('Proxy username is required')
    password = ''
    if user:
        same = all(previous.get(k) == v for k,v in [('protocol',protocol),('address',address),('port',int(port)),('user',user)])
        password = getpass.getpass('Proxy password' + ('; blank to keep saved password' if same else '') + ': ')
        if same and not password:
            password = previous['password']
    udp = False
    if protocol == 'socks':
        choice = ask('Does the provider support SOCKS5 UDP? y/n', 'y' if previous.get('udp') else 'n').lower()
        if choice not in ('y', 'n'):
            raise ValueError('Answer y or n for UDP support')
        udp = choice == 'y'
    state['egress_proxy'] = dict(protocol=protocol,address=address,port=int(port),user=user,password=password,udp=udp)


def configure(path, binary, previous=None):
    state = json.loads(Path(previous).read_text()) if previous else None
    previous_egress = (state or {}).get('egress', '')
    if state:
        print('Reconfigure preserves existing keys, credentials, panel paths and install mode.')
        mode = state['mode']
        main = domain(ask('Main domain', state['domain']))
    else:
        mode = {'1': 'xray', '2': 'marzban', '3': 'node'}.get(ask('Mode: 1 standalone, 2 panel, 3 node', '1'))
        if not mode:
            raise ValueError('Invalid install mode')
        main = domain(ask('Main domain'))
    names = {'grpc': [main], 'vision': []}
    for index in range(1, 5):
        name = ask(f'Extra SNI #{index}; blank to finish')
        if not name:
            break
        name = domain(name)
        if name in names['grpc'] + names['vision']:
            raise ValueError('Duplicate SNI')
        transport = ask('Transport: grpc or vision', 'grpc').lower()
        if transport not in names:
            raise ValueError('Invalid transport')
        names[transport].append(name)
    if state is None:
        state = new_state(mode, main, names, binary)
    state['domain'], state['names'] = main, names
    state['connection_name'] = ask('Connection name shown in your VPN client', state.get('connection_name', main[:64])).strip()
    state['ingress'] = state['egress'] = ''
    if mode == 'xray' and yes('Use separate ingress/egress IPv4 addresses'):
        state['ingress'], state['egress'] = ask('Ingress IPv4'), ask('Egress IPv4')
    if mode != 'node':
        configure_proxy(state)
    # A full egress proxy takes precedence over optional per-domain WARP routing.
    state['warp'] = mode == 'xray' and not state.get('egress_proxy') and yes('Use WARP for RU domains (fails closed if WARP later stops)')
    state['block_happ'] = mode == 'marzban' and yes('Block Happ User-Agent on subscriptions (can be spoofed)')
    if mode == 'node':
        state['panel_domain'] = domain(ask('Panel API domain; direct endpoint without CDN', state.get('panel_domain', '')))
        state['panel_user'] = ask('Panel sudo admin username', state.get('panel_user', ''))
        state['node_address'] = ask('Node address reachable from panel', state.get('node_address', main))
        state['node_name'] = ask('Unique node name', state.get('node_name', os.uname().nodename))
        state['management_sources'] = ask('Actual panel source IPs/CIDRs, comma separated (not CDN addresses)',
                                          ','.join(state.get('management_sources', []))).split(',')
        state['management_sources'] = [s.strip() for s in state['management_sources']]
    if yes('Prepare key-only SSH access for a non-root sudo user'):
        user = ask('SSH username', (state.get('ssh') or {}).get('user', 'operator'))
        port = ssh_port(ask('SSH port', str((state.get('ssh') or {}).get('port', 22))))
        public_key = ask('Full SSH public key')
        old_ssh = state.get('ssh') or {}
        state['ssh'] = {'user': user, 'port': port, 'public_key': public_key,
                        'password': (old_ssh.get('password') if old_ssh.get('user') == user else None) or secrets.token_hex(12)}
        state['ssh_confirmed'] = False
    if state.get('ssh') and state['egress'] != previous_egress:
        state['ssh_confirmed'] = False
    validate_state(state)
    save_json(path, state)


if __name__ == '__main__':
    try:
        configure(*sys.argv[1:])
    except (ValueError, EOFError) as error:
        raise SystemExit('ERROR: ' + str(error))
